name: mini-text2sql
services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # In Dockerfile: use ENV POSTGRES_PASSWORD=...
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    tty: true
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flask_text2sql:
    build: 
      context: .
      dockerfile: flask_text2sql.Dockerfile
    container_name: flask_text2sql
    depends_on:
      - postgres_db
    ports:
      - 5000:8080
